### ISSUE TITLE
Time argument  in `/timer cmd` is always 0, doesn't matter what I set it to.

### ISSUE THREAD

**Issue by TheFishy07** [NgLoader/Timer#1]
Hello, I've been trying to use your plugin and it's awesome! I just have this issue:
I have created a timer using `/timer create FiveSeconds 5s stop countdown` and have set 6 commands to it, one at each second from 5 to 0: `/timer cmd test addCommand 5 say 5` `/timer cmd test addCommand 4 say 4` `/timer cmd test addCommand 3 say 3` `/timer cmd test addCommand 2 say 2` `/timer cmd test addCommand 1 say 1` `/timer cmd test addCommand 0 say 0`.
But I don't know why when I enabled the timer `FiveSeconds` all the commands ran at the second 0.

How could I fix this?

Thanks for this amazing plugin!!!

**Comment by NgLoader** [comment]
Just write behinde the time the unit like "s" for seconds. when you write no unit behinde it is default to ticks.

You can also use multiply values like **2h10min** or **10min2h30s**
